lgrep: add more processes

diff --git a/lgrep b/lgrep
--- a/lgrep
+++ b/lgrep
@@ -21,55 +21,58 @@ usage()
 }
 
 PROCS=(
-	"active checks"         "acti chks"
-	"agent poller"          "ag poller"
-	"alerter"               "  alerter"
-	"alert manager"         "alrt mngr"
-	"alert syncer"          "alrt sncr"
-	"availability manager"  "avail mgr"
-	"collector"             "collector"
-	"configuration syncer"  "cfg syncr"
-	"connector manager"     "conn mngr"
-	"connector worker"      "conn wrkr"
-	"data sender"           "data sndr"
-	"db watchdog"           "db watchr"
-	"discoverer"            "discoverr"
-	"discovery manager"     "disc mngr"
-	"discovery worker"      "disc wrkr"
-	"escalator"             "escalator"
-	"ha manager"            "ha manger"
-	"heartbeat sender"      "hrtb sndr"
-	"history poller"        "hist polr"
-	"history syncer"        "hist sncr"
-	"housekeeper"           "hous kepr"
-	"http agent poller"     "ht ag plr"
-	"http poller"           "http pllr"
-	"ipmi manager"          "ipmi mngr"
-	"ipmi poller"           "ipmi pllr"
-	"icmp pinger"           "icmp pngr"
-	"java poller"           "jav pollr"
-	"listener"              " listener"
-	"lld manager"           "lld mangr"
-	"lld worker"            "lld workr"
-	"main process"          "main proc"
-	"node watcher"          "nod wtchr"
-	"odbc poller"           "odbcpollr"
-	"poller"                "   poller"
-	"preprocessing manager" "prep mngr"
-	"preprocessing worker"  "prep wrkr"
-	"proxy poller"          "prx pollr"
-	"report writer"         "rprt wrtr"
-	"report manager"        "rprt mngr"
-	"service manager"       "srvc mngr"
-	"snmp poller"           "snmp pllr"
-	"snmp trapper"          "snmp trpr"
-	"self-monitoring"       "  selfmon"
-	"task manager"          "task mngr"
-	"timer"                 "    timer"
-	"trapper"               "  trapper"
-	"trigger housekeeper"   "trg housk"
-	"unreachable poller"    "unr pollr"
-	"vmware collector"      "vmwr cltr"
+	"active checks"                "acti chks"
+	"agent poller"                 "ag poller"
+	"alerter"                      "  alerter"
+	"alert manager"                "alrt mngr"
+	"alert syncer"                 "alrt sncr"
+	"availability manager"         "avail mgr"
+	"collector"                    "collector"
+	"configuration syncer"         "cfg syncr"
+	"configuration syncer worker"  "cfg swrkr"
+	"connector manager"            "conn mngr"
+	"connector worker"             "conn wrkr"
+	"data sender"                  "data sndr"
+	"db watchdog"                  "db watchr"
+	"discoverer"                   "discoverr"
+	"discovery manager"            "disc mngr"
+	"discovery worker"             "disc wrkr"
+	"escalator"                    "escalator"
+	"ha manager"                   "ha manger"
+	"heartbeat sender"             "hrtb sndr"
+	"history poller"               "hist polr"
+	"history syncer"               "hist sncr"
+	"housekeeper"                  "hous kepr"
+	"http agent poller"            "http aplr"
+	"http poller"                  "http polr"
+	"internal poller"              "int pollr"
+	"ipmi manager"                 "ipmi mngr"
+	"ipmi poller"                  "ipmi polr"
+	"icmp pinger"                  "icmp pngr"
+	"java poller"                  "jav pollr"
+	"listener"                     " listener"
+	"lld manager"                  "lld mangr"
+	"lld worker"                   "lld workr"
+	"main process"                 "main proc"
+	"node watcher"                 "nod wtchr"
+	"odbc poller"                  "odbcpollr"
+	"poller"                       "   poller"
+	"preprocessing manager"        "prep mngr"
+	"preprocessing worker"         "prep wrkr"
+	"proxy poller"                 "prx pollr"
+	"report writer"                "rprt wrtr"
+	"report manager"               "rprt mngr"
+	"rsm"                          "      rsm"
+	"service manager"              "srvc mngr"
+	"snmp poller"                  "snmp pllr"
+	"snmp trapper"                 "snmp trpr"
+	"self-monitoring"              "  selfmon"
+	"task manager"                 "task mngr"
+	"timer"                        "    timer"
+	"trapper"                      "  trapper"
+	"trigger housekeeper"          "trg housk"
+	"unreachable poller"           "unr pollr"
+	"vmware collector"             "vmwr cltr"
 )
 
 [ $# -lt 2 ] && usage
@@ -114,7 +117,7 @@ egrep --color=none ' (server|proxy|agent) #[0-9]+ started \[[-a-z0-9 #]+\]$' $LO
     echo "$replace_ptrn" > $TMPF
 done
 
-[ -f $TMPF ] || die "no 'started [process]' messages in a log file"
+[ -f $TMPF ] || die "Cannot lgrep the log file, it was already rotated"
 
 replace_ptrn=$(cat $TMPF)
 rm -f $TMPF
